name: Basic Monkey Test Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  monkey-test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Playwright Monkey Test
        uses: ./
        with:
          url: 'https://playwright.dev'
          test-duration: '3'
          browser: 'chromium'
          max-actions: '50'
          action-delay: '2000'
          
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monkey-test-screenshots
          path: ./screenshots/
          retention-days: 7