name: GitHub-Hosted Runner Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      url:
        description: 'Target URL to test'
        required: false
        default: 'https://playwright.dev'
        type: string
      test-duration:
        description: 'Test duration in minutes'
        required: false
        default: '2'
        type: string
      browser:
        description: 'Browser to use'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      max-actions:
        description: 'Maximum number of actions'
        required: false
        default: '30'
        type: string

jobs:
  monkey-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run Playwright Monkey Test
        uses: ./
        with:
          url: ${{ github.event.inputs.url || 'https://playwright.dev' }}
          test-duration: ${{ github.event.inputs.test-duration || '2' }}
          browser: ${{ github.event.inputs.browser || 'chromium' }}
          max-actions: ${{ github.event.inputs.max-actions || '30' }}
          action-delay: '2000'
          
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monkey-test-screenshots-github-hosted
          path: ./screenshots/
          retention-days: 7